-- Add missing columns to jobs table for Phase 3A
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS parser_version VARCHAR DEFAULT NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS parsed_at TIMESTAMP DEFAULT NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS match_score INTEGER DEFAULT NULL;
